### ISSUE TITLE
video streaming doesn't work

### ISSUE THREAD

**Issue by posativ** [posativ/regenwolken#31]
maybe something content length related

```
2011-10-31 20:29:48 [8122] [ERROR] Error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/workers/sync.py", line 71, in handle
    self.handle_request(req, client, addr)
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/workers/sync.py", line 105, in handle_request
    resp.write(item)
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/http/wsgi.py", line 260, in write
    util.write(self.sock, arg, self.chunked)
  File "/usr/local/lib/python2.6/dist-packages/gunicorn/util.py", line 190, in write
    sock.sendall(data)
  File "<string>", line 1, in sendall
error: [Errno 104] Connection reset by peer
```

A gunicorn issue?

**Comment by posativ** [comment]
`lighttpd` issue, use `nginx` ;)
