### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Connection'

### ISSUE THREAD

**Issue by keithah** [posativ/regenwolken#47]
So trying this on Linux and getting:
keith@sea:~/tmp$ regenwolken &
[1] 5264
keith@sea:~/tmp$ /usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/keith/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/regenwolken", line 9, in <module>
    load_entry_point('regenwolken==0.6.2', 'console_scripts', 'regenwolken')()
  File "/usr/local/lib/python2.7/dist-packages/regenwolken-0.6.2-py2.7.egg/regenwolken/**init**.py", line 140, in main
    app = Regenwolken()
  File "/usr/local/lib/python2.7/dist-packages/regenwolken-0.6.2-py2.7.egg/regenwolken/**init**.py", line 53, in **init**
    self.setup_mongodb()
  File "/usr/local/lib/python2.7/dist-packages/regenwolken-0.6.2-py2.7.egg/regenwolken/**init**.py", line 91, in setup_mongodb
    con = pymongo.Connection(
AttributeError: 'module' object has no attribute 'Connection'

Any ideas?

**Comment by posativ** [comment]
`pymongo.Connection` has been removed in 2.4 or higher. Try with an older version of PyMongo.
